#!/usr/bin/env python3
"""Wrapper script for BlipEraser Privileged Daemon.

This script is installed to /usr/lib/blip-eraser/blip-eraser-privileged
and invoked by the systemd service.
"""

import os
import sys


INSTALL_ROOT = os.path.dirname(os.path.abspath(__file__))
if INSTALL_ROOT not in sys.path:
    sys.path.insert(0, INSTALL_ROOT)

from blip_eraser.daemon.privileged_daemon import main

if __name__ == "__main__":
    sys.exit(main())